title: "The Male Gaze: Heroine's and Damsel's in 2000's Science Fiction"
description: "How does the term 'male gaze' make the transition from film to academia to 2000's science fiction? This project examines how academia prior to the first film of the decade manifests this film theory term, how the films embody the male gaze, and how contemporary sources aim to combat it in theory and practice."
show_downloads: false
theme: jekyll-theme-hacker
